name:                structural-xml
version:             0.1.0.0
description:         Structural parsing and generation of XML data.
license:             BSD3
license-file:        LICENSE
copyright:           (c) 2022 Frederik Ramcke, Eir Försäkring AB
author:              Federik Ramcke <frederik.ramcke@eirforsakring.se>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- xml-conduit
- mtl
- bytestring

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- RecordWildCards
- StrictData
- DuplicateRecordFields
- FlexibleInstances
- NamedFieldPuns

ghc-options:
- -Weverything
- -Wno-missing-import-lists
- -Wno-implicit-prelude
- -Wno-unsafe
- -Wno-safe
- -Wno-missing-local-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-all-missed-specialisations
library:
  source-dirs: src

