name:                structural-xml-generics
version:             0.2.0.2
description:         Derive XML (un)parsers generically
license:             BSD3
license-file:        LICENSE
copyright:           (c) 2023 Frederik Ramcke, Eir Försäkring AB
author:              Frederik Ramcke <frederikramcke@mailbox.org>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- mtl
- generics-sop
- structural-xml

default-extensions:
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- RecordWildCards
- StrictData
- DuplicateRecordFields
- FlexibleInstances
- NamedFieldPuns
- DataKinds
- EmptyCase
- TypeFamilies
- TypeOperators
- UndecidableInstances
- AllowAmbiguousTypes
- MultiParamTypeClasses

ghc-options:
- -Werror
- -Weverything
- -Wno-missing-import-lists
- -Wno-implicit-prelude
- -Wno-unsafe
- -Wno-missing-kind-signatures
- -Wno-safe
- -Wno-missing-local-signatures
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-all-missed-specialisations
- -Wno-missing-export-lists
library:
  source-dirs: src

